### ISSUE TITLE
Install on Linux 

### ISSUE THREAD

**Issue by DMTarmey** [sentient-engineering/agent-q#5]
Im running arch and finding it difficult to get running and have plenty of experience in installing software like this but can seem to get this to deploy to Linux properly

**Comment by DMTarmey** [comment]
poetry install
Installing dependencies from lock file

Installing the current project: agentq (0.1.0)Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/cleo/application.py", line 316, in run
    exit_code = self._run(io)
                ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/console/application.py", line 190, in _run
    exit_code: int = super()._run(io)
                     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cleo/application.py", line 420, in _run
    exit_code = self._run_command(command, io)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cleo/application.py", line 462, in _run_command
    raise error
  File "/usr/lib/python3.12/site-packages/cleo/application.py", line 446, in _run_command
    exit_code = command.run(io)
                ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cleo/commands/base_command.py", line 117, in run
    return self.execute(io) or 0
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cleo/commands/command.py", line 61, in execute
    return self.handle()
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/console/commands/install.py", line 183, in handle
    builder.build()
  File "/usr/lib/python3.12/site-packages/poetry/masonry/builders/editable.py", line 77, in build
    added_files += self._add_pth()
                   ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/masonry/builders/editable.py", line 110, in _add_pth
    for include in self._module.includes
                   ^^^^^^^^^^^^
  File "/usr/lib/python3.12/functools.py", line 993, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/core/masonry/builders/builder.py", line 97, in _module
    return Module(
           ^^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/core/masonry/utils/module.py", line 75, in __init__
    PackageInclude(
  File "/usr/lib/python3.12/site-packages/poetry/core/masonry/utils/package_include.py", line 31, in __init__
    self.check_elements()
  File "/usr/lib/python3.12/site-packages/poetry/core/masonry/utils/package_include.py", line 72, in check_elements
    raise ValueError(
ValueError: /home/dmtarmey/Programming/Agent-Q/agentq does not contain any element

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cleo/application.py", line 327, in run
    self.render_error(e, io)
  File "/usr/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Application' object has no attribute 'set_solution_provider_repository'. Did you mean: '_get_solution_provider_repository'?

 ╭─dmtarmey@dmtarmey in ~/Programming/Agent-Q is  v1.0.0 via  v18.20.5 via  v3.12.7 (venv) took 0s
[🔴] ×    ls ~/Programming/Agent-Q/agentq
ls: cannot access '/home/dmtarmey/Programming/Agent-Q/agentq': No such file or directory

 ╭─dmtarmey@dmtarmey in ~/Programming/Agent-Q is  v1.0.0 via  v18.20.5 via  v3.12.7 (venv) took 0s
[🔴] ×   ls ~/Programming/Agent-Q/agent-q
AgentQ.txt  core             log_files    output.txt          README.md         test
asyncio     dpo_pairs.jsonl  logs         playwright_test.py  requirements.txt  user_preferences
cat         __init__.py      logs.txt     poetry.lock         server.py         utils
config      LICENSE          __main__.py  __pycache__         temp

 ╭─dmtarmey@dmtarmey in ~/Programming/Agent-Q is  v1.0.0 via  v18.20.5 via  v3.12.7 (venv) took 0s
 ╰─λ touch ~/Programming/Agent-Q/agent-q/__init__.py

 ╭─dmtarmey@dmtarmey in ~/Programming/Agent-Q is  v1.0.0 via  v18.20.5 via  v3.12.7 (venv) took 0s
 ╰─λ    poetry install --no-root
Installing dependencies from lock file

**Comment by DMTarmey** [comment]
i worked it out
